### ISSUE TITLE
CMS: Static Media not found

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#12]
The links in the tool are (statue & such) are not working due to a CMS Bug.

Copied form https://pep.pad.foebud.org/coop-web:

    Uploading media (png, pdf, mov), media not found afterwards. 

    Not Found

    Beispiel Link:

    https://webtest.pep.coop/static/media/uploads/pEpDocs/pepcoop_manifest.pdf

    The requested URL /static/media/uploads/pEpDocs/pepcoop_manifest.pdf was not found on this server.

    Maybe helpful: https://stackoverflow.com/a/46063519/1457385

**Comment by ari-pep** [comment]
this was fixed by mezzanine serving its own static content
