### ISSUE TITLE
Add SEPA Data in Join

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#21]
**INFO**
Lass uns als namens Konvention für Vorlagen die neu erstellt werden müssen volgendes nehmen:

altername_de.pdf  -> altername_sepa_de.pdf

**JOIN**
Nur wenn "Country" ein EU-Land ist:

Checkbox: Ich möchte dass der Monatsbeitrag per Lastschrift von folgendem Konto eingezogen wird:
Name der Bank: ___________
IBAN: : ___________
BIC: : ___________ 
Checken dass nichts leer ist.

**AFM**
Angepasstes AFM Formular verwenden wenn SEPA Option gewählt.

**BACKEND**
Daten in Mitglieds sichtbar machen.

** Rechnungsversand Mails**
andere Rechnungsversandmail schicken (hier deine Rechnung für deine Unterlagen, wurde schon abgebucht. (die Vorlage mache ich dir)

**EXPORT**
Machen wir später.

**Comment by ari-pep** [comment]
Europa != EU (habs im issue geaendert). Als einwohner eines europaeischen nicht-EU-Landes bin ich da pingelig ;)

**Comment by buffstop** [comment]
> Europa != EU

Deshalb habe ich Europa geschrieben. Bitte Europa nehmen. "_Europäische_ Genossenschaft".
Hintergrund: Auch wenn es offiziell funktionieren soll habe ich von vielen Problemen gelesen, dass EU Banken oft Lastschriften aus Deutschland verweigern.

Und weil es dir eine Herzenssache ist, und pEP kind of Schwizerisch ist: nimm die Schweiz auch mit rein.

Also

EUROPA + SCHWEIZ

**Comment by buffstop** [comment]
Sorry for the mess.

**Comment by buffstop** [comment]
Adjusted AFMs pushed:
pEp-coop-AFM_sepa_en.pdf
pEp-coop-AFM_sepa_de.pdf

The field names in the documents are:

accountOwner
nameOfBank
iban
bic

**Comment by buffstop** [comment]
Before implementing, make sure you checked depending issue #28 to avoid double work.

**Comment by ari-pep** [comment]
ready for review

**Comment by buffstop** [comment]
Did not test intensively, looks good so far.
I can choose Sepa Direct Debit also when country is set to other. But that is low prio, v.1.1
