### ISSUE TITLE
EntryFee for Companies

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#28]
HIGH PRIO

We have a new requirement. 
Companies have to make an additional one time payment as entry fee of 90 €.

Additional AFMs have already been created. Their filenames are:

    pEp-coop-AFM-companies-de
    pEp-coop-AFM-companies-en
    pEp-coop-AFM-companies_sepa_de
    pEp-coop-AFM-companies_sepa_en

**ToDo:**

If the user is not a natural person:
- fill & offer for download the corresponding AFM (see filenames above)
- Add 90 € to the sum to pay: (numShares * 10) + 90 _in all corresponding forms and mails_:
* AFMs
* Remider mails
* probably forgot some here ..

**Comment by ari-pep** [comment]
do sustaining / supporting members count as company? phrased differently: everyone but individuals have to pay this fee?

**Comment by buffstop** [comment]
> everyone but individuals have to pay this fee?
Yes

**Comment by ari-pep** [comment]
ready for review

**Comment by buffstop** [comment]
The amount in the AFM is wrong. I applied with a big company (90€), one share (10€).

**The AFM says:**
> Den Betrag für die Genossenschaftsanteile plus Eintrittsgeld werden wir nach erhalt des unterschrieben Formulars unter Verwendung folgender Daten per Lastschrift einziehen.
Kontoinhaber: p≡p coop SCE 
Betrag (€): 10
Verwendungszweck: p≡p coop shares  IQSPGORUQ0

Den Monatsbeitrag ziehen wir wie gewünscht per Lastschrift ein.

**Expected:**
Betrag (€): 100
(90 +10)

**Comment by ari-pep** [comment]
was fixed
