### ISSUE TITLE
Wrong Urkunde_Hintergrund_blank.pdf, Cache?

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#40]
Even the correct PepCoopMembership/certificate/Urkunde_Hintergrund_blank.pdf is in place, the old one (titled: "FEHLT ...") is used for creation of certificates. Is it chached somehow? If so please please clean chache.

**Comment by ari-pep** [comment]
I know there are issues attached to this one, since the immediate thing is cleared I'm closing this  just for sake of a better "uebersicht"
