### ISSUE TITLE
Join: Sum shares keeps 10 €

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#47]
**Repro:**
- set number of shares to 2, using the text field, not the slider

**Expected:**
Sum is 20€

**Actual:**
Sum is 10 €

**Comment by ari-pep** [comment]
Didn't manage to fix this. I guess the only workaround for now is to just remove the Sum field. With our share_price of 10€ it's not hard to work out what you have to pay, and it's written on the page after that anyway
