### ISSUE TITLE
New Data Not Visible in Backend

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#57]
Viewing the details of a membership application in backend, all data we (pEp) has added is not displayed nor editable.

- Type Monthly Fee
- Entry fee
- Sepa/Transfer choice
- Bank data
- the unique code (for transfer checking aso)
- All I forgot :-)

Example: https://yes.pep.coop/detail/96

ToDo:
Make sure all data the user provides is visible and editable in backend.

**Comment by ari-pep** [comment]
related: member_type now in dashboard
