### ISSUE TITLE
Server Errror Downloading AFM

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#64]
A user infomrmed us he can not download the AFM. 

**User Error Description:**
Hallo und Guten Abend.

Etwas geht schief beim Herunterladen des Antragsformulars

https://join.pep.coop/pEp_coop_SCE_AFM_name.pdf

Beim Anklicken und beim kopieren in den Web Browser Firefox erhalte ich
die gleiche Fehler Meldung Internal Server Error....

Wenn ich den Bestand pEp_coop_SCE_AFM_NAME.pdf
herunterlade und zu öffnen versuche, meldet der Adobe Reader, dass der
Bestand nicht geöffnet werden kann.

Was tun, sprach Zeus ...

**Comment by buffstop** [comment]
Ich teste das mal eben.

**Comment by buffstop** [comment]
I just tried to test it. I did not even get the "verify your email" email.

**Comment by ari-pep** [comment]
the issue is umlaute. I think you noticed this before, but there's no open Issue I think

on it
