### ISSUE TITLE
dead-paper-AFM mail-confirmation broken (was: confirm email: Internal Server Error)

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#67]
Clicking my "confirm email" link, I get an error:

"Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)
"
The mail is from 1.5., maybe an expiration triggers the issue.

**#####**
Email

[english version below]

Hallo Andreas Buff,

möchten wir Dich bitten uns kurz zu bestätigen, dass diese E-Mail-Adresse korrekt ist und Du auf diesem
Wege erreichbar bist. Dafür brauchst Du nur den folgenden Link aufzurufen:

  https://join.pep.coop/vae/0SJ23AUB9F/5341MNB9P3VWZ/autobuff@gmx.de

Solltest Du nicht Andreas Buff sein und diese Adresse nicht bei uns angegeben haben,
antworte bitte kurz auf diese E-Mail. Dann werden wir die Adresse aus unser
Datenbank streichen.

Antworte bitte ebenfalls, falls Du die E-Mail-Adresse ändern möchtest.

Viele Grüße :: Das p≡p coop Team

**Comment by ari-pep** [comment]
This is really the mail you received? because you've arrived on another view

could you try this with 
`
https://join.pep.coop/verify/autobuff@gmx.de/0SJ23AUB9F
`

**Comment by ari-pep** [comment]
Oh, I see where you're coming from: 
I misinterpreted a button in the dashboard - I tried to verify your email, but instead the button sends out verification mails for people that have gone only through dead-paper registration forms - a route that none of our members have taken
The good thing is: people cannot reach this by themselves, admins  have to press the mail conf
The not so good: I triggered sending such an email to all founding members

**Comment by ari-pep** [comment]
The actual issue: There's a button that looks like it would override mail confirmation on /dashboard, but it does not - it sends out a new mail confirmation mail that is slightly different and is broken on our fork. Asking upstream wether it's broken for them as well.

[code says something about 30C3...](https://github.com/ari-pep/PepCoopMembership/blob/7de7442d0859314a0723a25afc8f83b31bfeaf11/c3smembership/__init__.py#L106)

**Comment by ari-pep** [comment]
I've disallowed the route (1af2a1c) and it's hidden on the dashboard (bf20053). Not removing it because I don't want to diverge from upstream unnecessarily.
