### ISSUE TITLE
Can not open member details

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#7]
Error trying to see details for member.

**Repro:**
- Log in to backend
- Show list of members
- Click on the member number (first, left, item in a row of the member list)

**Expected:**
Details for member shown.

**Actual:**
Error:
Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)

**Comment by ari-pep** [comment]
fixed (18e4e64)

**Comment by buffstop** [comment]
Shows up here with current 

https://join.pep.coop/detail/5

**Comment by ari-pep** [comment]
I think these are two bugs. the one I fixed before only helped with candidate members. currently in staging I fixed the other one concerning accepted members. Have to confirm this when going live with 1.0.1
