### ISSUE TITLE
mType Status

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#71]
In the backend of the production system, applyee#11 is the only applyee that has (had) a button in collumn "mtype status".

I clicked it and the below mail was sent to applyee#11

I wonder under which circumstances this button appears in backend.
Also I wonder if we should simply remove the button from backend or if we can tweak it for something useful in our workflow.

**ToDo:**
Think about the purpose of the button and what we should do with it. Remove or tweak.
Currently it is dangerous that someone could accidentally click it due to obvious reasons.

**####**

INFO: in the given link replace nameOfApplyee with the first name of the applyee (her...i).

Hallo nameOfApplyee

gemeinsam mit Dir freuen wir uns auf die erste Generalversammlung der C3S SCE
am 23. August, um 14:00 Uhr im Millowitsch-Theater in Köln. Details dazu
erhältst Du in Kürze in einer separaten Einladung.

Von Dir fehlt uns aktuell noch eine Angabe dazu, ob Du nutzendes (ordentliches)
Mitglied oder investierendes (nicht-ordentliches) Mitglied werden möchtest bzw.
kannst. Gemäß der Satzung der C3S SCE [1] müssen ordentliche Mitglieder in der
Lage sein, uns mindestes drei eigene Musikwerke zur Verwertung zu übertragen.
In der Generalversammlung sind zudem ausschließlich ordentliche Mitglieder
stimmberechtigt. Außerdem ist es für uns wichtig zu wissen, ob Du bereits
Mitglied einer anderen Verwertungsgesellschaft in Deutschland oder auch im
Ausland bist.

Um es so einfach wie möglich zu gestalten, geben wir Dir einen individuellen
Link zu einer Webpage, auf der Du uns mit wenigen Klicks mit Deinen
Informationen versorgen kannst:

  https://join.pep.coop/mtype/3F5RGR2YQ4/51TZGVJC41SRM/nameOfApplyee@vecirex.net

Dort findest Du alle relevanten Hinweise und Erklärungen, die Dir die Wahl
erleichtern. Bleiben dennoch Fragen, schreibe uns bitte unter members-admin@pep.coop

Bitte ergänze Deine Angaben bis zum 10. Juli 2014. Erhalten wir bis zum 10.
Juli keine Angaben von Dir, gehen wir davon aus, dass Du investierendes
Mitglied (ohne Stimmrecht) werden möchtest.

Nicht vergessen, please spread the word: Wir suchen ständig aktive Supporter
und Neumitglieder. Wer als bestehendes Mitglied seine Anteile aufstocken will,
muss momentan noch das Formular für Neumitglieder nutzen [2]. Wir führen die
Daten anschließend zusammen. Wer uns dagegen monatlich helfen möchte, unsere
laufenden Kosten zu bestreiten, kann uns unter dem Motto "I sustain C3S" mit
regelmäßigen, kleinen Beiträgen unterstützen [3].

Genießt den Sommer, und freut Euch mit uns auf eine faire Bezahlung für Musiker
mit der C3S!

Viele Grüße

Das Team der C3S

[1] https://archive.c3s.cc/aktuell/legal/C3S_SCE_de.pdf

[2] https://yes.c3s.cc

[3] https://sustain.c3s.cc

++++++++++++++++++ I sustain C3S! ++++++++++++++++++
+++ Dein Beitrag zu fairer Bezahlung für Musiker +++
+++            https://sustain.c3s.cc            +++
+++                                              +++
+++     Support fair remuneration for artists    +++
+++          https://sustain.c3s.cc/?en          +++
++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by ari-pep** [comment]
this is a connected to the membership_type, where we only have one category.
in testing the whole column is gone.
