### ISSUE TITLE
Button to Export Members and applyies as CSV

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#76]
Implement a button in backend (or introduce a certain URL is fine also to not mess with the UI), that offers an CSV export of all member and applyees for download. The following fields should be exported as columns, ideally with column header titles, in given order:

id
membership_number
firstname
lastname
address1
address2
postcode
city
country
email
num_shares
member_type
fee
entry_fee
payment_method
payment_sdd_iban
payment_sdd_bic
payment_sdd_bankname
date_of_submission
email_is_confirmed
signature_received
payment_received
accountant_comment
date_of_birth
membership_loss_type

Please have a look with your eagles eyes, most probably I forgot something obviously.

**Comment by ari-pep** [comment]
what's NULL sopposed to be? (i.e. membership no is initially NULL)

did you leave these out on purpose?
- signature_received_date
- signatue_confirmed_date
- payment_received_date
- payment_confirmed_date
- membership_loss_date,type
- certificate_email,+date

otherwise, it looks fine to me

**Comment by buffstop** [comment]
> what's NULL sopposed to be? (i.e. membership no is initially NULL)

I am not sure what's the best value here for sheets. Please simply use empty string, 1.1.1970, other common default values. I might ask to change that later though :-/

> did you leave these out on purpose?

My idea is to:
- Handle the easy and working things in the tool (sign received, payment for shares received, send reminder mails)
- Do everything else in Excel sheet
- export only stuff that is of use in an excel sheet when administer members (to avoid sheet explosion)
- add custom columns, that are managed in the sheet, to the right of the sheet, so you can always copy & past a new export over the existing data without loosing the content of the custom collumns.

Thus imo  the following is not of interest. Only _that_ we received payment/signature.  

So yes, I intentionally excluded the following:
    signature_received_date 
    signatue_confirmed_date
    payment_received_date
    payment_confirmed_date 
    certificate_email,+date

I was not aware of this:
membership_loss_date,type

What is the membership_loss_type? That sounds interesting.

**Comment by ari-pep** [comment]
regarding datasheet explosion: It might be helpful to separate (two csvs):
- reoccuring business (fee collection, general assembly invitation)
- non-reoccuring business (entry and all things related, purchase of additional shares, exit (membership_loss)) 

ack wrt null, excluding: 1.1.1970 is particularly evil. To unix-people it stands out of course, but to everybody else it seems like a normal new year. We have people with birthday in 1970 already and I needed to double-check wether that's not some error

membership_loss_type: one of [resignation, expulsion, death, bankruptcy, winding-up, shares_transfer] where the last is the transfer of all remaining shares. Some apply only to humans (death), some only to legal persons (winding-up). Check out editing an existing member.

**Comment by buffstop** [comment]
> regarding datasheet explosion: It might be helpful to separate (two csvs):

maybe YAGNI. Lets implement only what we currently need.

> ... excluding: 1.1.1970 is particularly evil...

Aggree. Use "0000-00-00", adapted to the date format of your choice.

> membership_loss_type: one of [resignation, expulsion, death, bankruptcy, winding-up, shares_transfer] 

Please export this also.  Updated description.

**Comment by ari-pep** [comment]
JFYI: 1970-01-01 is currently in production so this is going to be 1970-01-01 -> 0000-00-00

otherwise ack and afaics ready to go

**Comment by ari-pep** [comment]
@buffstop: there's now /admin/admin.csv on testing, please check wether it matches your intentions

**Comment by buffstop** [comment]
testing is down.

> Service Unavailable

> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by ari-pep** [comment]
my fault, sorry - up again

**Comment by buffstop** [comment]
Looks good to me. Only thing missing is "id". Also I changed my mind with certain fields and removed them from the list. Sorry.
Left ToDo:
- Add "id" as first collumn
- Remove the following:

payment_received_date
email_confirm_mail_date
membership_loss_date
membership_date

**Comment by ari-pep** [comment]
changes are in testing

**Comment by buffstop** [comment]
Looks fine for a first version. It will take me some time to deal with it and find potential problems. I will create new tickets in case of problems.
Thx!

**Comment by buffstop** [comment]
PS: Please tripple-check that the export is not available without certificate or minor tricking.

**Comment by buffstop** [comment]
Export is (currently?) unavailable on production (join).
404 Not Found

**Comment by ari-pep** [comment]
weird - the code was not in production, but I'm pretty sure at some point it was. Anyway: fixed
