### ISSUE TITLE
Proxy Error trying to register

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#78]
User sagt:

> 1) Nach Eingabe Ihrer Daten, "weiter" klicken.
> 2) Daten überprüfen und "Bestätigungs-E-Mail schicken" klicken.

Hier kommt die Fehlermeldung:
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /check_email.

**Comment by ari-pep** [comment]
Someone killed postfix -.-
